Комментарии
hodakoov/advertising_site pull request #10
Opened 2023-11-04 11:57 UTC by LuSP19

2023-11-04 15:52 UTC, hodakoov approved these changes
like

2023-11-06 13:55 UTC, technogleb requested changes
Напишу еще тут пару моментов чтобы не забыть, не по этому конкретному PR.

1) В create_user.py не спрашивается email. Если я хочу создать юзера вручную, сделать его админом и указать его почту, такой возможности нет. 
2) В целом мы думали, что можно сделать осмысленное в админке - можно сделать функционал для указания какого-то пользователя админом.

В целом по коду с комментами замечаний нет, есть один вопрос.

2023-11-06 13:55 UTC, technogleb commented on app/models/comment.py
Я уже отписывал мимоходом в PR#9 у Валеры замечания по верхнеуровнем моделям. Не совсем понятно, зачем ты создал папку models/ в которую кладешь по файлику на каждую модель. Пока кажется в этом нет необходимости и можно просто создать на верхнем уровне файлик models.py и туда положить все модели.

2023-11-06 13:55 UTC, technogleb commented on app/models/comment.py
> +    user = relationship('User', backref='comments')
Гуд

2023-11-06 13:55 UTC, technogleb commented on app/user/views.py
> +        return redirect(get_redirect_target())
не совсем понимаю, как он здесь понимает, что нужно идти на 'index.index'

2023-11-06 14:25 UTC, technogleb commented on app/utils.py
> +    for target in request.values.get('next'), request.referrer:
Думаю, чтобы пофиксить ошибку с зацикливанием, нужно вставить в `get` дефолтное значение, которое будет возвращаться, если нет `next`. 
И первым if обрабатывать это значение.

2023-11-08 15:32 UTC, technogleb approved these changes
Все гуд!

2023-11-08 15:35 UTC, merged