Скрипты для создания и загрузки фейковых данных в БД
hodakoov/advertising_site pull request #3
Opened 2023-10-01 11:11 UTC by hodakoov

2023-10-02 13:37 UTC, technogleb requested changes
Понимаю, что это скрипт на коленке, который ты выложил "как есть", но я все равно отревьюил.

2023-10-02 13:37 UTC, technogleb commented on fake_data/add_data.py
> +            save_salary_data(row)
Тут неправильная архитектура, функция называется `read_csv`, а по факту делает аж две вещи  - считывает файл и использует `save_salary_data` чтобы загнать строки в бд. 
Кроме того, само наличие двух модулей для этой задачи избыточно. 

Вместо этого нужно сделать вот такую архитектуру в одном модуле. 

```python
def get_fake_row():
    # делает все то, что у тебя
    ...

def generate_data(num_rows=50):
    for _ in range(num_rows):
        row = get_fake_row()
        yield row

def save_to_csv(f, row):
    # позволяет сохранять output генератора в файл
    ...

def save_to_db(row):
    # делает то, что у тебя делает функция `save_salary_data`


if __name__ == "__main__":
    # здесь можно написать какой-то код, который спрашивает куда сохранять
    if write_to_db:
        app = create_app()
        with app.app_context():
            for row in generate_data():
                save_to_db(row)
    else:
        with open(filename, 'w') as f:
            for row in generate_data():
                save_to_csv(f, row)
```

2023-10-02 13:37 UTC, technogleb commented on fake_data/create_data.py
> +            ]
Вроде я в файле с code style писал про правила переноса.

2023-10-02 16:09 UTC, LuSP19 approved these changes

2023-10-14 10:08 UTC, technogleb requested changes
В остальном все супер.

2023-10-14 10:08 UTC, technogleb commented on fake_data/generate_fake_data.py
> +                        '-> ')
Правила переноса.
```python
input(
    'first long line'
    'second long line'
)
```

2023-10-14 10:08 UTC, technogleb commented on fake_data/generate_fake_data.py
> +    write_to_db = input('Выберите место сохранения данных:\n'
Если переменная называется  `write_to_db`, то подразумевается что она должна быть boolean типа. И уж точно по ней нельзя догадаться, что она может подразумевать запись в csv.

Тут лучше спросить записывать в бд или нет, после чего если пользователь ввел `Y/y`, то записывать в бд, если нет, то в csv

2023-10-15 09:47 UTC, technogleb approved these changes
Теперь меня все устраивает.

2023-10-15 09:55 UTC, merged