Добавил скрапер объявлений
hodakoov/advertising_site pull request #4
Opened 2023-10-02 15:50 UTC by LuSP19

2023-10-02 20:25 UTC, hodakoov commented on app/scraper.py
> +from __init__ import create_app
как я понял, надо делать from app import create_app

2023-10-03 16:29 UTC, hodakoov approved these changes

2023-10-03 16:29 UTC, hodakoov commented on app/scraper.py
> +from __init__ import create_app
как я понял, надо делать from app import create_app

2023-10-14 11:29 UTC, technogleb requested changes
В целом, старался придираться как мог и нашел только два замечания.
В остальном, все круто!

2023-10-14 11:29 UTC, technogleb commented on app/scraper.py
> +}
Чтобы парсить русские имена месяцев в питоне, можно установить локаль, после чего попробовать найти соответствующий placeholder в `strptime`.  Пример. ниже:

```python
import locale
from datetime import datetime


locale.setlocale(locale.LC_TIME, 'ru_RU.UTF-8')
dt = datetime.strptime('24-января-17 07:50', '%d-%B-%y %H:%M')
```

2023-10-14 11:29 UTC, technogleb commented on app/scraper.py
> +        write_ads_to_db(ads)
Вот логика записи ads в базу данных мне кажется излишней в этой функции.

Пусть лучше будет вот так.
```python
if __name__ == "__main__":
    app = create_app()
    with app.app_context():
        initial_url = app.config['SCRAPER_INITIAL_URL']
        page_limit = app.config['SCRAPER_PAGE_LIMIT']
        delay_limit = app.config['SCRAPER_DELAY_LIMIT']
        
        ads = scrap_ads(initial_url, page_limit, delay_limit)
        write_ads_to_db(ads)
```

2023-10-19 17:34 UTC, technogleb approved these changes
Хорошо, мерджу.

2023-10-19 17:35 UTC, merged