CRUD объявлений
hodakoov/advertising_site pull request #9
Opened 2023-11-04 11:49 UTC by hodakoov

Все таки добил и загружаемые картинки скачиваются в папку media и оттуда же отображаются в шаблонах. Сохранение  SQLite тоже реализовал, но не пустил в продакшн, т.к. при декодировании картинки компьютер зависал (отобразил буквально пару раз).

2023-11-04 18:09 UTC, hodakoov commented
Добавил возможность загружать несколько картинок

2023-11-05 10:26 UTC, LuSP19 approved these changes

2023-11-06 14:34 UTC, technogleb requested changes
Так, прежде всего замечания идут по переделанной структуре проекта, с которой я не согласен. 

Смотри, сейчас в мастере такая структура:
```md
* admin/
# сюда идут вьюхи, модели, формы и прочее, относящееся к админу
- - __init__.py
- - views.py
* user/
# сюда идут вьюхи, модели, формы и прочее, относящееся к юзеру
- - __init__.py
- - views.py
- - forms.py
- - models.py
- - decorators.py
* routes.py  # это общие вьюхи которые не попадают в какую-либо категорию (впрочем, это нужно переименовать в views.py для единообразия)
* models/
# сюда идут общие модели, которые являются общими для всех других категорий
# Это нужно вытащить из директории на уровень выше и назвать просто models.py
# если появится какая-то более сложная дихотомия, тогда можно уже и общую функциональность засовывать в папочки
- - post.py
```

У тебя появляются две дополнительные директории user_advertisements и show_advertisements. Но, функциональность первой директории относится чисто к юзерам и должна быть внутри юзера, вторая же показывать объявление в целом для всех, поэтому логично должна оставаться просто в routes.py (которую нужно переименовать во views.py) и models.py

2023-11-06 14:34 UTC, technogleb commented on .gitignore
> +app.db
почему-то убрал пустую строку в конце

2023-11-08 15:52 UTC, technogleb approved these changes

2023-11-08 16:01 UTC, merged